### ISSUE TITLE
Custom Fields Data in Taxonomies

### ISSUE THREAD

**Issue by dnavarrojr** [WP-API/WP-API.github.io#48]
I have a custom Taxonomy with two custom fields.  The data in the custom fields is not showing up in the json data.  I didn't see anything in the docs about it.

**Comment by dnavarrojr** [comment]
So, is meta-data not included with Taxonomies?

**Comment by dnavarrojr** [comment]
Is this plugin no longer supported?

**Comment by tarunmarkose** [comment]
I am also looking for an answer to this...

**Comment by danielbachhuber** [comment]
Please see http://v2.wp-api.org/extending/modifying/

You can use `register_rest_field()` with your custom taxonomy.
